server:
  port: 8080
  compression:
    enabled: true

management:
  endpoints:
    enabled-by-default: true

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'WARN'
    
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mchudgins/config-props.git
